# Generated by Django 3.0.4 on 2020-04-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsForm',
        ),
    ]
