# Generated by Django 3.0.4 on 2020-04-05 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_delete_newsform'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
