# Generated by Django 3.0.4 on 2020-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200405_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_title',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
