# Generated by Django 3.0.4 on 2020-04-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_title',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
