# Generated by Django 3.0.4 on 2020-04-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
