# Generated by Django 3.0.4 on 2020-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200408_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=False, unique=True),
            preserve_default=False,
        ),
    ]
