# Generated by Django 3.0.4 on 2020-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20200408_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='about.png', null=True, upload_to=''),
        ),
    ]
